Repository ballerine-io/ballerine, pull requests merged in 2024-05, with the labels that each got.

#2332 chore(tm): adding mappings, brand names
  services/workflows-service/src/errors.ts
  services/workflows-service/src/transaction/dtos/transaction-create.dto.ts
  services/workflows-service/src/transaction/transaction.mapper.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2335 EndUser ongoing monitoring
  services/workflows-service/prisma/migrations/20240430113758_add_monitoring_and_aml_columns_to_end_user/migration.sql
  services/workflows-service/prisma/schema.prisma
  services/workflows-service/src/end-user/end-user.schema.ts
  services/workflows-service/src/end-user/end-user.service.ts
  services/workflows-service/src/webhooks/webhooks.service.ts
  services/workflows-service/src/workflow/hook-callback-handler.service.ts
  services/workflows-service/src/workflow/schemas/zod-schemas.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2336 Transaction monitoring error handling fixes, tests fixes
  services/workflows-service/package.json
  services/workflows-service/src/common/abstract-logger/abstract-logger.ts
  services/workflows-service/src/common/app-logger/app-logger.service.ts
  services/workflows-service/src/common/filters/HttpExceptions.filter.ts
  services/workflows-service/src/common/utils/winston-logger/winston-logger.ts
  services/workflows-service/src/errors.ts
  services/workflows-service/src/transaction/transaction.controller.external.intg.test.ts
  services/workflows-service/src/transaction/transaction.controller.external.ts
  services/workflows-service/src/transaction/transaction.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2342 Made ID in transaction monitoring table to not look like a link
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/components/AlertsTable/columns.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlertsAnalysis/components/AlertAnalysisTable/columns.tsx
Labels: enhancement, Review effort [1-5]: 2

#2344 fix(err-handling): prisma error guard
  services/workflows-service/src/prisma/prisma.util.ts
  services/workflows-service/src/transaction/transaction.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#2355 Fix individuals profiles kyc enum
  apps/backoffice-v2/src/pages/Profiles/Individuals/components/ProfilesTable/columns.tsx
Labels: bug_fix, Review effort [1-5]: 2

#2357 Fix page resetting from url on refresh
  apps/backoffice-v2/src/common/hooks/useIsMounted/useIsMounted.tsx
  apps/backoffice-v2/src/common/hooks/useSearch/useSearch.tsx
Labels: enhancement, Review effort [1-5]: 2

#2358 Renamed id column to correlation id
  apps/backoffice-v2/src/pages/Profiles/Individuals/components/ProfilesTable/columns.tsx
Labels: enhancement, Review effort [1-5]: 1

#2359 Ongoing monitoring no hits fix
  services/workflows-service/src/webhooks/webhooks.service.ts
Labels: enhancement, Review effort [1-5]: 2

#2362 Remove `headless-example` image creation GitHub Action workflow
  .github/workflows/publish-headless-example.yml
Labels: bug_fix, Review effort [1-5]: 1

#2376 Added buildFlat to @ballerine/blocks
  apps/backoffice-v2/CHANGELOG.md
  apps/backoffice-v2/package.json
  apps/kyb-app/CHANGELOG.md
  apps/kyb-app/package.json
  packages/blocks/.eslintrc.cjs
  packages/blocks/CHANGELOG.md
  packages/blocks/package.json
  packages/blocks/src/blocks.spec-d.ts
  packages/blocks/src/blocks.spec.ts
  packages/blocks/src/blocks.ts
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4

#2381 Added error to sentry scope
  services/workflows-service/src/sentry/sentry.service.ts
Labels: Review effort [1-5]: 2, Bug fix

#2353 BAL-1964 - Transaction monitoring - add dormant rule
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/alert/alert.service.intg.test.ts
  services/workflows-service/src/common/filters/HttpExceptions.filter.ts
  services/workflows-service/src/data-analytics/data-analytics.service.ts
  services/workflows-service/src/data-analytics/types.ts
  services/workflows-service/src/transaction/test-utils/transaction-factory.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2371 feat: enabled download button for all document file types
  apps/backoffice-v2/src/common/components/molecules/DownloadFile/DownloadFile.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/Case.Documents.Toolbar.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/Case.Documents.tsx
Labels: enhancement, Review effort [1-5]: 2

#2372 Added logs to AML webhook
  services/workflows-service/src/webhooks/webhooks.service.ts
  services/workflows-service/src/workflow/workflow.service.ts
Labels: enhancement, Review effort [1-5]: 2

#2375 feat: reworked back to portal button logic
  apps/kyb-app/src/components/layouts/AppShell/Navigation.tsx
  apps/kyb-app/src/hooks/useAppExit/useAppExit.ts
  apps/kyb-app/src/pages/CollectionFlow/components/pages/Approved/Approved.tsx
  apps/kyb-app/src/pages/CollectionFlow/components/pages/Success/Success.tsx
Labels: enhancement, Review effort [1-5]: 2

#2373 fix: fixed case page layout
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/DefaultBlocks.tsx
  apps/backoffice-v2/src/pages/CaseManagement/CaseManagement.page.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/Case.Actions.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/Case.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/actions-variants/DefaultActions/DefaultActions.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 3, Bug fix

#2374 BAL-1957
  apps/backoffice-v2/CHANGELOG.md
  apps/backoffice-v2/package.json
  apps/backoffice-v2/src/domains/entities/hooks/mutations/useApproveTaskByIdMutation/useApproveTaskByIdMutation.tsx
  apps/backoffice-v2/src/domains/workflows/fetchers.ts
  apps/backoffice-v2/src/lib/blocks/components/KycBlock/hooks/useKycBlock/useKycBlock.tsx
  apps/backoffice-v2/src/lib/blocks/hooks/useDocumentBlocks/hooks/useCommentInputLogic/useCommentInputLogic.ts
  apps/backoffice-v2/src/lib/blocks/hooks/useDocumentBlocks/useDocumentBlocks.tsx
  apps/kyb-app/CHANGELOG.md
  apps/kyb-app/package.json
  examples/headless-example/CHANGELOG.md
  examples/headless-example/package.json
  packages/common/CHANGELOG.md
  packages/common/package.json
  packages/common/src/schemas/documents/default-context-schema.ts
  packages/workflow-core/CHANGELOG.md
  packages/workflow-core/package.json
  pnpm-lock.yaml
  sdks/web-ui-sdk/CHANGELOG.md
  sdks/web-ui-sdk/package.json
  sdks/workflow-browser-sdk/CHANGELOG.md
  sdks/workflow-browser-sdk/package.json
  sdks/workflow-node-sdk/CHANGELOG.md
  sdks/workflow-node-sdk/package.json
  services/workflows-service/CHANGELOG.md
  services/workflows-service/package.json
  services/workflows-service/src/workflow/dtos/document-decision-update-input.ts
  services/workflows-service/src/workflow/workflow.controller.internal.ts
  services/workflows-service/src/workflow/workflow.service.ts
  websites/docs/package.json
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2138 fix: removed reduntant public flag from collection flow endpoints
  services/workflows-service/src/collection-flow/controllers/collection-flow.business.controller.ts
  services/workflows-service/src/collection-flow/controllers/collection-flow.controller.ts
  services/workflows-service/src/collection-flow/controllers/collection-flow.end-user.controller.ts
  services/workflows-service/src/collection-flow/controllers/collection-flow.files.controller.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 2
