Repository ballerine-io/ballerine, pull requests merged in 2024-03, with the labels that each got.

#2148 Upgraded workflows-service TypeScript version
  pnpm-lock.yaml
  services/workflows-service/package.json
  services/workflows-service/src/business/business.controller.external.ts
  services/workflows-service/src/business/business.controller.internal.ts
  services/workflows-service/src/business/business.controller.ts
  services/workflows-service/src/common/access-control/acl.module.ts
  services/workflows-service/src/common/access-control/interceptors/acl-filter-response.interceptor.ts
  services/workflows-service/src/common/access-control/interceptors/acl-validate-request.interceptor.ts
  services/workflows-service/src/end-user/end-user.controller.external.ts
  services/workflows-service/src/end-user/end-user.controller.internal.ts
  services/workflows-service/src/filter/filter.controller.external.ts
  services/workflows-service/src/filter/filter.controller.internal.ts
  services/workflows-service/src/storage/storage.controller.external.ts
  services/workflows-service/src/storage/storage.controller.internal.ts
  services/workflows-service/src/test/helpers/nest-app-helper.ts
  services/workflows-service/src/workflow/workflow.controller.external.ts
  services/workflows-service/src/workflow/workflow.controller.external.unit.test.ts
  services/workflows-service/src/workflow/workflow.controller.internal.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4, Possible security concern

#2154 Ts seed error fix
  pnpm-lock.yaml
  services/workflows-service/package.json
Labels: enhancement, Review effort [1-5]: 2, other

#2155 fix: fixed bug where event was dispatched when form isnt valid
  apps/kyb-app/src/components/organisms/UIRenderer/elements/SubmitButton/SubmitButton.tsx
Labels: bug_fix, Review effort [1-5]: 2

#2156 chore(translation): cn translation fix 'optional'
  apps/kyb-app/public/locales/cn/translation.json
Labels: enhancement, Review effort [1-5]: 1

#2122 feat(ballerine_install.sh): add ballerine_install.sh script to automa…
  ballerine_install.sh
  deploy/README.md
  deploy/docker-compose-build.yml
  deploy/scripts/boot.sh
Labels: documentation, enhancement, Review effort [1-5]: 3

#2149 feat: add ballerine ansible automation
  .gitignore
  deploy/ansible/ballerine_playbook/README.md
  deploy/ansible/ballerine_playbook/ballerine-playbook.yml
  deploy/ansible/ballerine_playbook/inventory.txt
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/defaults/main.yml
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/tasks/install-docker.yml
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/tasks/main.yml
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/tasks/setup-ballerine.yml
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/tasks/start-docker.yml
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/templates/Caddyfile.j2
Labels: documentation, enhancement, Review effort [1-5]: 4, other

#2163 fix: fixed bug where case creation button been displayed on any case
  apps/backoffice-v2/src/pages/Entities/components/CaseCreation/CaseCreation.tsx
Labels: bug_fix, Review effort [1-5]: 2

#2169 Bal 1627
  apps/backoffice-v2/package.json
  apps/backoffice-v2/src/common/components/organisms/Toaster/Toaster.tsx
  apps/backoffice-v2/src/main.tsx
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 2

#2172 Add `assignedAt` to the document decision webhook
  services/workflows-service/src/events/document-changed-webhook-caller.ts
  services/workflows-service/src/workflow/types/index.ts
  services/workflows-service/src/workflow/workflow.service.ts
Labels: enhancement, Review effort [1-5]: 2

#2175 quick fix for stale state in kyb-app
  apps/kyb-app/src/components/layouts/AppShell/LanguagePicker.tsx
  apps/kyb-app/src/hooks/useLanguageParam/useLanguageParam.ts
Labels: enhancement, Review effort [1-5]: 2

#2188 transaltion fix cn
  services/workflows-service/src/providers/translation/locales/cn/translation.json
Labels: enhancement, Review effort [1-5]: 1

#2194 Bal 1354 dedupe v2
  services/workflows-service/prisma/migrations/20240313003439_dedupe_strategy/migration.sql
  services/workflows-service/prisma/schema.prisma
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/alert/alert.repository.ts
  services/workflows-service/src/alert/alert.service.ts
  services/workflows-service/src/alert/types.ts
  services/workflows-service/src/common/utils/sign/sign.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2204 Bal 1648 fetch transaction counterparty
  apps/backoffice-v2/src/domains/alerts/fetchers.ts
  apps/backoffice-v2/src/domains/transactions/fetchers.ts
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/components/AlertsTable/columns.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlertsAnalysis/TransactionMonitoringAlertsAnalysis.page.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlertsAnalysis/components/AlertAnalysisTable/columns.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlertsAnalysis/hooks/useTransactionMonitoringAlertsAnalysisPageLogic/useTransactionMonitoringAlertsAnalysisPageLogic.tsx
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/scripts/alerts/generate-transactions.ts
  services/workflows-service/src/alert/alert.controller.external.ts
  services/workflows-service/src/transaction/transaction.controller.external.ts
Labels: enhancement, Review effort [1-5]: 2

#2218 chore: update version
  apps/backoffice-v2/CHANGELOG.md
  apps/backoffice-v2/package.json
  apps/kyb-app/CHANGELOG.md
  apps/kyb-app/package.json
  apps/workflows-dashboard/CHANGELOG.md
  apps/workflows-dashboard/package.json
  examples/headless-example/CHANGELOG.md
  examples/headless-example/package.json
  examples/report-generation-example/CHANGELOG.md
  examples/report-generation-example/package.json
  packages/blocks/CHANGELOG.md
  packages/blocks/package.json
  packages/common/CHANGELOG.md
  packages/common/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/eslint-config-react/CHANGELOG.md
  packages/eslint-config-react/package.json
  packages/eslint-config/CHANGELOG.md
  packages/eslint-config/package.json
  packages/react-pdf-toolkit/CHANGELOG.md
  packages/react-pdf-toolkit/package.json
  packages/rules-engine/CHANGELOG.md
  packages/rules-engine/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
  packages/workflow-core/CHANGELOG.md
  packages/workflow-core/package.json
  pnpm-lock.yaml
  sdks/web-ui-sdk/CHANGELOG.md
  sdks/web-ui-sdk/package.json
  sdks/workflow-browser-sdk/CHANGELOG.md
  sdks/workflow-browser-sdk/package.json
  sdks/workflow-node-sdk/CHANGELOG.md
  sdks/workflow-node-sdk/package.json
  services/websocket-service/CHANGELOG.md
  services/websocket-service/package.json
  services/workflows-service/CHANGELOG.md
  services/workflows-service/package.json
  websites/docs/package.json
Labels: enhancement, Review effort [1-5]: 2

#2232 Feature/implement report hook return
  services/workflows-service/prisma/migrations/20240319101225_create_business_report/migration.sql
  services/workflows-service/prisma/schema.prisma
  services/workflows-service/src/business-report/business-report.module.ts
  services/workflows-service/src/collection-flow/collection-flow.module.ts
  services/workflows-service/src/common/middlewares/auth-key.middleware.ts
  services/workflows-service/src/customer/customer.service.ts
  services/workflows-service/src/customer/types.ts
  services/workflows-service/src/webhooks/webhooks.module.ts
  services/workflows-service/src/workflow/cron/ongoing-monitoring.cron.intg.test.ts
  services/workflows-service/src/workflow/cron/ongoing-monitoring.cron.ts
  services/workflows-service/src/workflow/hook-callback-handler.service.ts
  services/workflows-service/src/workflow/types/unified-callback-names.ts
  services/workflows-service/src/workflow/workflow.module.ts
Labels: enhancement, Review effort [1-5]: 4

#2220 Removed webhook secret env variable
  deploy/ansible/ballerine_playbook/roles/setup-ballerine/tasks/setup-ballerine.yml
  deploy/docker-compose-build.yml
  deploy/helm/example.values.yaml
  services/workflows-service/.env.example
  services/workflows-service/src/env.ts
  services/workflows-service/src/events/document-changed-webhook-caller.ts
  services/workflows-service/src/events/workflow-completed-webhook-caller.ts
  services/workflows-service/src/events/workflow-state-changed-webhook-caller.ts
  services/workflows-service/src/workflow/workflow.service.unit.test.ts
Labels: enhancement, Review effort [1-5]: 2

#2251 bal 1776 fix transaction type based rule
  services/workflows-service/src/alert/alert.service.intg.test.ts
  services/workflows-service/src/data-analytics/data-analytics.service.ts
  services/workflows-service/src/data-analytics/types.ts
  services/workflows-service/src/test/db-setup.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2255 fix: add outputs for ci
  .github/workflows/publish-workflows-service.yml
Labels: enhancement, Review effort [1-5]: 2

#2258 bal 1642 sentry ecosystem upload source map
  .github/actions/bump-version/dist/index.js
  .github/actions/bump-version/index.js
  .github/workflows/publish-workflows-service.yml
  services/workflows-service/Dockerfile
  services/workflows-service/src/env.ts
  services/workflows-service/src/sentry/sentry.module.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2254 Feat: Manage releases using tags and add sentry release
  .github/actions/bump-version/action.yml
  .github/actions/bump-version/dist/index.js
  .github/actions/bump-version/index.js
  .github/actions/bump-version/package-lock.json
  .github/actions/bump-version/package.json
  .github/workflows/publish-workflows-service.yml
  services/workflows-service/Dockerfile
  services/workflows-service/src/env.ts
  services/workflows-service/src/sentry/sentry.module.ts
Labels: enhancement, Review effort [1-5]: 3
