Repository ballerine-io/ballerine, pull requests merged in 2024-02, with the labels that each got.

#2098 bal 1439 fix env var
  apps/backoffice-v2/.env.example
Labels: bug_fix, Review effort [1-5]: 1, Possible security concern

#2101 fix: swagger
  services/workflows-service/src/main.ts
  services/workflows-service/src/swagger.ts
  services/workflows-service/src/swagger/swagger.controller.ts
  services/workflows-service/src/swagger/swagger.ts
Labels: enhancement, Review effort [1-5]: 3

#2105 Fixed new status applying on decision
  apps/backoffice-v2/src/common/components/organisms/Header/Header.Navbar.tsx
  apps/backoffice-v2/src/common/hooks/useZodSearchParams/useZodSearchParams.tsx
  apps/backoffice-v2/src/common/utils/check-is-loosely-equal-deep/check-is-loosely-equal-deep.tsx
  apps/backoffice-v2/src/lib/zod/utils/checkers/index.ts
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/components/AlertsFilters/AlertsFilters.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/components/AlertsTable/AlertsTable.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/get-alerts-search-schema.ts
  pnpm-lock.yaml
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2107 Bal 1427 alert definition v3
  services/workflows-service/package.json
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/data-analytics/consts.ts
  services/workflows-service/src/data-analytics/data-analytics.repository/evaluate-transactions-against-dynamic-rules.ts
  services/workflows-service/src/data-analytics/data-analytics.service.ts
  services/workflows-service/src/data-analytics/evaluate-types.ts
Labels: enhancement, Review effort [1-5]: 4

#2111 Added AI commit messages
  .github/workflows/ci.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#2116 fix: fixed bug where finish event was sent on continue clicks
  apps/kyb-app/src/components/organisms/UIRenderer/elements/SubmitButton/SubmitButton.tsx
Labels: enhancement, bug_fix, Review effort [1-5]: 2
