Repository ballerine-io/ballerine, pull requests merged in 2024-04, with the labels that each got.

#2286 fix(core): add log to childworkflow creation
  .changeset/lazy-hounds-dream.md
  .changeset/pre.json
  apps/backoffice-v2/CHANGELOG.md
  apps/backoffice-v2/package.json
  apps/kyb-app/CHANGELOG.md
  apps/kyb-app/package.json
  apps/kyb-app/src/components/organisms/DynamicUI/StateManager/components/ActionsHandler/action-handlers/plugin-runner.handler.ts
  examples/headless-example/CHANGELOG.md
  examples/headless-example/package.json
  packages/workflow-core/CHANGELOG.md
  packages/workflow-core/package.json
  packages/workflow-core/src/lib/plugins/common-plugin/child-workflow-plugin.ts
  packages/workflow-core/src/lib/workflow-runner.ts
  pnpm-lock.yaml
  sdks/workflow-browser-sdk/CHANGELOG.md
  sdks/workflow-browser-sdk/package.json
  sdks/workflow-node-sdk/CHANGELOG.md
  sdks/workflow-node-sdk/package.json
  services/workflows-service/CHANGELOG.md
  services/workflows-service/package.json
  services/workflows-service/src/workflow/workflow.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2292 fix: fixed missing conditional rendering of process tracker
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/hooks/useCaseBlocksLogic/utils/get-tabs-block-map.tsx
  apps/backoffice-v2/src/lib/blocks/variants/WebsiteMonitoringBlocks/WebsiteMonitoringBlocks.tsx
Labels: bug_fix, Review effort [1-5]: 2

#2294 Fixed process tracker signature
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/constants.tsx
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/interfaces.ts
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/process-tracker-adapters/collection-flow.process-tracker.ts
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/process-tracker-adapters/merchant-monitoring.process-tracker.ts
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/process-tracker-adapters/process-tracker.abstract.ts
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/process-tracker-adapters/third-party.proces-tracker.tsx
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/hooks/useProcessTracker/useProcessTracker.tsx
  apps/backoffice-v2/src/common/components/molecules/ProcessTracker/interfaces.ts
  apps/backoffice-v2/src/lib/blocks/hooks/useProcessTrackerBlock/useProcessTrackerBlock.tsx
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/hooks/useCaseBlocksLogic/utils/get-tabs-block-map.tsx
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/hooks/useDefaultBlocksLogic/useDefaultBlocksLogic.tsx
  apps/backoffice-v2/src/lib/blocks/variants/KybExampleBlocks/KybExampleBlocks.tsx
  apps/backoffice-v2/src/lib/blocks/variants/ManualReviewBlocks/ManualReviewBlocks.tsx
  apps/backoffice-v2/src/lib/blocks/variants/WebsiteMonitoringBlocks/WebsiteMonitoringBlocks.tsx
  apps/backoffice-v2/src/pages/Entity/hooks/useCasePlugins/useCasePlugins.tsx
Labels: enhancement, Review effort [1-5]: 2

#2302 Fix tests
  services/workflows-service/src/workflow/cron/ongoing-monitoring.cron.intg.test.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#2309 feat: added theme schemas to common & updated imports & bump
  apps/backoffice-v2/CHANGELOG.md
  apps/backoffice-v2/package.json
  apps/backoffice-v2/src/domains/workflow-definitions/enums/workflow-definition-config-theme.ts
  apps/backoffice-v2/src/domains/workflow-definitions/fetchers.ts
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/hooks/useCaseBlocksLogic/utils/get-tabs-block-map.tsx
  apps/backoffice-v2/src/lib/blocks/variants/DefaultBlocks/hooks/useCaseBlocksLogic/utils/get-variant-tabs.ts
  apps/kyb-app/CHANGELOG.md
  apps/kyb-app/package.json
  examples/headless-example/CHANGELOG.md
  examples/headless-example/package.json
  packages/common/CHANGELOG.md
  packages/common/package.json
  packages/common/src/consts/index.ts
  packages/common/src/index.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/workflow/workflow-config-theme.ts
  packages/workflow-core/CHANGELOG.md
  packages/workflow-core/package.json
  pnpm-lock.yaml
  sdks/web-ui-sdk/CHANGELOG.md
  sdks/web-ui-sdk/package.json
  sdks/workflow-browser-sdk/CHANGELOG.md
  sdks/workflow-browser-sdk/package.json
  sdks/workflow-node-sdk/CHANGELOG.md
  sdks/workflow-node-sdk/package.json
  services/workflows-service/CHANGELOG.md
  services/workflows-service/package.json
  services/workflows-service/src/workflow/schemas/zod-schemas.ts
  websites/docs/package.json
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2306 TM Alert rules - STRUC_CC & STRUC_APM
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/alert/alert.service.intg.test.ts
  services/workflows-service/src/data-analytics/data-analytics.service.ts
  services/workflows-service/src/transaction/test-utils/transaction-factory.ts
Labels: enhancement, Review effort [1-5]: 4, Bug fix

#2316 Fix pagination search query serializer
  apps/backoffice-v2/src/common/hooks/usePagination/usePagination.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2317 fix: remove alert type
  services/workflows-service/prisma/migrations/20240424132721_remove_alert_type/migration.sql
  services/workflows-service/prisma/schema.prisma
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/alert/dtos/create-alert-definition.dto.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2318 fix: remove alert type from front and also update dedupe logic
  apps/backoffice-v2/src/domains/alerts/fetchers.ts
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/components/AlertsFilters/AlertsFilters.tsx
  apps/backoffice-v2/src/pages/TransactionMonitoringAlerts/get-alerts-search-schema.ts
  services/workflows-service/scripts/alerts/generate-alerts.ts
  services/workflows-service/src/alert/alert.service.intg.test.ts
  services/workflows-service/src/alert/consts.ts
  services/workflows-service/src/data-analytics/data-analytics.service.intg.test.ts
  services/workflows-service/src/data-analytics/types.ts
  services/workflows-service/src/test/db-teardown.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2322 Fix document ids on update flow
  .vscode/launch.json
  services/workflows-service/src/workflow/workflow.service.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#2325 Removed wrong id
  services/workflows-service/src/webhooks/webhooks.service.ts
Labels: enhancement, Review effort [1-5]: 2

#2326 feat(tm): add alt endpoint
  apps/backoffice-v2/src/domains/transactions/fetchers.ts
  services/workflows-service/prisma/migrations/20240425200207_tm_model_changes/migration.sql
  services/workflows-service/prisma/migrations/20240426063346_adding_apm/migration.sql
  services/workflows-service/prisma/schema.prisma
  services/workflows-service/src/business/dtos/business-create.ts
  services/workflows-service/src/transaction/dtos/bulk-transactions-created.dto.ts
  services/workflows-service/src/transaction/dtos/transaction-create.dto.ts
  services/workflows-service/src/transaction/test-utils/transaction-factory.ts
  services/workflows-service/src/transaction/transaction.controller.external.ts
  services/workflows-service/src/transaction/transaction.mapper.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2329 chore(tm): adding mappings
  services/workflows-service/src/transaction/transaction.mapper.ts
Labels: enhancement, Review effort [1-5]: 2
