Repository ballerine-io/ballerine, pull requests merged in 2024-06, with the labels that each got.

#2368 fix: fixed validation errors duplicates
  apps/kyb-app/src/components/organisms/DynamicUI/rule-engines/json-schema.rule-engine.ts
Labels: bug_fix, Review effort [1-5]: 2, Bug fix

#2331 Pdf export feature
  apps/backoffice-v2/package.json
  apps/backoffice-v2/public/locales/en/toast.json
  apps/backoffice-v2/src/common/utils/svg-to-png/svg-to-png.ts
  apps/backoffice-v2/src/common/utils/value-or-none/value-or-none.ts
  apps/backoffice-v2/src/domains/customer/fetchers.ts
  apps/backoffice-v2/src/domains/workflows/fetchers.ts
  apps/backoffice-v2/src/lib/blocks/hooks/useUbosRegistryProvidedBlock/useUbosRegistryProvidedBlock.tsx
  apps/backoffice-v2/src/main.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/Case.Actions.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/CaseOptions.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/mutations/useGeneratePDFMutation/useGeneratePDFMutation.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/company-ownership-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/company-sanctions-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/identity-verifications-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/individual-sanctions-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/pdf-renderer.abstract.ts
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/registry-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/renderers/title-page.pdf.tsx
  apps/backoffice-v2/src/pages/Entity/components/Case/components/CaseOptions/hooks/useCaseOptionsLogic/useCaseOptionsLogic.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/assets/title-page-ballerine-logo.png
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/components/CaseInformationDisclaimer/CaseInformationDisclaimer.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/components/CaseInformationPageContainer/CaseInformationPageContainer.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/components/CaseInformationPageHeader/CaseInformationPageHeader.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/components/CaseInformationPageSection/CaseInformationPageSection.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/components/CaseInformationPageSectionHeader/CaseInformationPageSectionHeader.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanyOwnershipPage/CompanyOwnershipPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanyOwnershipPage/EmptyCompanyOwnershipPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanyOwnershipPage/company-ownership.schema.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanyOwnershipPage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanySanctionsPage/CompanySanctionsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanySanctionsPage/EmptyCompanySanctionsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanySanctionsPage/company-sanctions.schema.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanySanctionsPage/components/CompanySanctionsMatchSection/CompanySanctionsMatchSection.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/CompanySanctionsPage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IdentityVerificationsPage/EmptyIdentityVerificationsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IdentityVerificationsPage/IdentityVerificationsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IdentityVerificationsPage/components/IdentityItem/IdentityItem.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IdentityVerificationsPage/identity-verifications.schema.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IdentityVerificationsPage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/EmptyIndividualSanctionsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/IndividualSanctionsPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/components/IndividualSanctionsItem/IndividualSanctionsItem.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/components/IndividualSanctionsItem/ValueOrNone.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/IndividualSanctionsPage/individual-sanctions.schema.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/EmptyRegistryInformationPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/RegistryInformationPage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/registry-information.schema.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/types.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/RegistryInformationPage/utils/create-registry-items.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/TitlePage/TitlePage.tsx
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/pages/TitlePage/index.ts
  apps/backoffice-v2/src/pages/Entity/pdfs/case-information/schemas/base-case-information-pdf.schema.ts
  pnpm-lock.yaml
  services/workflows-service/scripts/seed.ts
Labels: enhancement, Review effort [1-5]: 4

#2177 [docs]:Update installation steps for ballerine
  websites/docs/astro.config.mjs
  websites/docs/src/content/docs/en/deployment/ansible_deployment.mdx
  websites/docs/src/content/docs/en/deployment/docker_compose.mdx
  websites/docs/src/content/docs/en/getting_started/deployment.mdx
Labels: documentation, enhancement, Review effort [1-5]: 2
